force-app/main/default/objects/Case/fields/Clockify_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Clockify_Task_Id__c</fullName>
    <description>Clockify Task Id</description>
    <externalId>true</externalId>
    <label>Clockify Task Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/ClockifyProjectID__c.field-meta.xml
<CustomField>
    <fullName>ClockifyProjectID__c</fullName>
    <externalId>true</externalId>
    <label>ClockifyProjectID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time entries object from Clockify integration, which is integrated with Cases and Accounts</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship from Case object</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/ClockifyTimeEntryId__c.field-meta.xml
<CustomField>
    <fullName>ClockifyTimeEntryId__c</fullName>
    <description>Clockify Time Entry ID from integration</description>
    <externalId>true</externalId>
    <label>Clockify Time Entry ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field with time entry description to integrate with Clockify</description>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End time from Time Entry</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/isBillable__c.field-meta.xml
<CustomField>
    <fullName>isBillable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to check if the time entry is billable or not. This will reflect on the hours presented to customer and on it&apos;s entitlements</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time from Time Entry</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User IDs from Time Entries</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/ClockifyUserId__c.field-meta.xml
<CustomField>
    <fullName>ClockifyUserId__c</fullName>
    <description>Clockify User ID. This is not generated automatically, it must be updated by an user</description>
    <externalId>true</externalId>
    <label>Clockify User ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TimeEntryAPI_Handler.cls
public class TimeEntryAPI_Handler {
    public static void createAPI(RestRequest req){
        TimeEntryWrapper timeEntry = TimeEntryWrapper.parse(req.requestBody.toString());
        if(!validateEntry(timeEntry)){
            new IntegrationLogCreator('Clockify-API', 'Create-Manually', 'Time Entry failed Validation', 'Ignored', Json.serialize(timeEntry)).publish();
            return;
        }
        retrieveObjects(timeEntry, new TimeEntry__c());
    }
    public static void updateAPI(RestRequest req){
        TimeEntryWrapper timeEntry = TimeEntryWrapper.parse(req.requestBody.toString());
        if(!validateEntry(timeEntry)){
            new IntegrationLogCreator('Clockify-API', 'Update', 'Time Entry failed Validation', 'Ignored', Json.serialize(timeEntry)).publish();
            return;
        }
        List<TimeEntry__c> databaseEntry = new List<TimeEntry__c>();
        databaseEntry.addAll([SELECT ID, ClockifyTimeEntryId__c, StartTime__c, EndTime__c, Description__c, UserId__c, CaseId__c
                                 FROM TimeEntry__c WHERE ClockifyTimeEntryId__c=:timeEntry.id LIMIT 1]);
        if(!databaseEntry.isEmpty()){
            retrieveObjects(timeEntry, databaseEntry[0]);
        }else{
            retrieveObjects(timeEntry, new TimeEntry__c());
        }
    }
    public static void deleteAPI(RestRequest req){
        TimeEntryWrapper timeEntry = TimeEntryWrapper.parse(req.requestBody.toString());
        List<TimeEntry__c> databaseEntry = new List<TimeEntry__c>();
        databaseEntry.addAll([SELECT ID FROM TimeEntry__c WHERE ClockifyTimeEntryId__c=:timeEntry.id LIMIT 1]);
        if(!databaseEntry.isEmpty()){
            delete databaseEntry[0];
        }else{
            new IntegrationLogCreator('Clockify-API', 'Delete', 'Time Entry not found in database', 'Ignored', Json.serialize(timeEntry)).publish();
        }
    }
    private static Boolean validateEntry(TimeEntryWrapper timeEntry){
        if(String.isBlank(timeEntry.projectId) || 
            String.isBlank(timeEntry.workspaceId) || 
                String.isBlank(timeEntry.userId)){
                    return false;
        }
        return true;
    }
    private static void retrieveObjects(TimeEntryWrapper timeEntry, TimeEntry__c entry){
        List<User> entryUser = new List<User>();
        entryUser.addAll([SELECT ID FROM User WHERE ClockifyUserId__c =:timeEntry.userId LIMIT 1]);
        List<ServiceContract> entryProject = new List<ServiceContract>();
        entryProject.addAll([SELECT ID FROM ServiceContract WHERE ClockifyProjectId__c=:timeEntry.projectId LIMIT 1]);
        if(entryUser.isEmpty() || entryProject.isEmpty()){
            new IntegrationLogCreator('Clockify-API', 'Retrieve-Objects', 'Project or User not found', 'Ignored', Json.serialize(timeEntry)).publish();
            return;
        }
        if(timeEntry.task != null){
            List<Case> entryTask = new List<Case>();
            entryTask.addAll([SELECT ID, EntitlementId FROM Case WHERE Clockify_Task_Id__c=:timeEntry.task.id LIMIT 1]);
            ID task = entryTask.isEmpty() ? null : entryTask[0].ID;
            upsertEntry(entryUser[0], entryProject[0], task, timeEntry, entry);
        }else{
            upsertEntry(entryUser[0], entryProject[0], timeEntry, entry);
        }
    }
    private static void upsertEntry(User entryUser, ServiceContract entryProject, ID entryTask, TimeEntryWrapper timeEntry, TimeEntry__c entry){    
        entry.CaseId__c = entryTask;
        upsertEntry(entryUser, entryProject, timeEntry, entry);
    }
    private static void upsertEntry(User entryUser, ServiceContract entryProject, TimeEntryWrapper timeEntry, TimeEntry__c entry){
        entry.ClockifyTimeEntryId__c = timeEntry.id;
        entry.StartTime__c = getZuluDate(timeEntry.timeInterval.start);
        entry.EndTime__c = getZuluDate(timeEntry.timeInterval.end_x);
        entry.Description__c = timeEntry.description;
        entry.isBillable__c = timeEntry.billable;
        entry.UserId__c = entryUser.ID;
        entry.Service_Contract__c = entryProject.ID;
        upsert entry;
    }
    private static Datetime getZuluDate(String zulu) {
        Datetime d = Datetime.valueOf(zulu.replace('T',' '));
        return d;
    }
}