force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/ClockifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Clockify Settings</label>
</CustomObject>

force-app/main/default/objects/ClockifySettings__c/fields/LogsLifeTime__c.field-meta.xml
<CustomField>
    <fullName>LogsLifeTime__c</fullName>
    <description>Em dias</description>
    <label>LogsLifeTime</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Create_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Create_Key__c</fullName>
    <label>Signing Create Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Delete_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Delete_Key__c</fullName>
    <label>Signing Delete Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Stop_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Stop_Key__c</fullName>
    <label>Signing Stop Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Update_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Update_Key__c</fullName>
    <label>Signing Update Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/ClockifyProjectID__c.field-meta.xml
<CustomField>
    <fullName>ClockifyProjectID__c</fullName>
    <externalId>true</externalId>
    <label>ClockifyProjectID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time entries object from Clockify integration, which is integrated with Cases and Accounts</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship from Case object</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/ClockifyTimeEntryId__c.field-meta.xml
<CustomField>
    <fullName>ClockifyTimeEntryId__c</fullName>
    <description>Clockify Time Entry ID from integration</description>
    <externalId>true</externalId>
    <label>Clockify Time Entry ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field with time entry description to integrate with Clockify</description>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End time from Time Entry</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time from Time Entry</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/testFactory.cls
public class testFactory {
    public static TimeEntry__c createTimeEntry(String entryId, String caseId, String description, DateTime startTime, DateTime endTime, String projectId){
        TimeEntry__c te = new TimeEntry__c();
        te.ClockifyTimeEntryId__c = entryId;
        te.CaseId__c = caseId;
        te.Description__c = description;
        te.StartTime__c = startTime;
        te.EndTime__c = endTime;
        te.Service_Contract__c = projectId;
        return te;
    }
    public static ServiceContract createServiceContract(String name, String accId, String projectId){
        ServiceContract cront = new ServiceContract();
        cront.Name = name;
        cront.AccountId = accId;
        cront.ClockifyProjectId__c = projectId;
        cront.StartDate = Date.today().addDays(-1);
        return cront;
    }
    public static ClockifySettings__c createSettings(String workspaceId, String updatekey, String stopKey, String deleteKey, String createKey, Integer logsTime){
        ClockifySettings__c clockS = new ClockifySettings__c();
        clockS.workspaceId__c = workspaceId;
        clockS.Signing_Update_Key__c = updatekey;
        clockS.Signing_Stop_Key__c = stopKey;
        clockS.Signing_Delete_Key__c = deleteKey;
        clockS.Signing_Create_Key__c = createKey;
        clockS.LogsLifeTime__c = logsTime;
        return clockS;
    }
    public static Case createCase(String subject, String status){
        Case ld = new Case();
        ld.Subject = subject;
        ld.Status = status;
        ld.LastModifiedDate = Date.today().addDays(-8);
        return ld;
    }
}