force-app/main/default/objects/Case/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/TotalHoursPerContract__c.field-meta.xml
<CustomField>
    <fullName>TotalHoursPerContract__c</fullName>
    <label>Total Hours Per Contract</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time entries object from Clockify integration, which is integrated with Cases and Accounts</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship from Case object</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field with time entry description to integrate with Clockify</description>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>End time from Time Entry</description>
    <label>End Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/isBillable__c.field-meta.xml
<CustomField>
    <fullName>isBillable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to check if the time entry is billable or not. This will reflect on the hours presented to customer and on it&apos;s entitlements</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time from Time Entry</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ClientReportTest.cls
@isTest
public class ClientReportTest {
	
    @isTest
    public static void reportCreation(){
        String projectName = 'Test Project', taskName = 'Test Task', timeName = 'TIME-1', timeNote = 'DG Time Note';
        DateTime startDate = Datetime.now().addHours(-3);
        DateTime endDate = Datetime.now();
        Decimal contractedHours = 10, timeHours = 3;
        ServiceContract project = new ServiceContract(Name = projectName, TotalHoursPerContract__c = contractedHours);
        insert project;
        Case task = new Case(Subject = taskName, Service_Contract__c = project.Id, Status = 'New', Origin = 'Email');
        insert task;
       	TimeEntry__c timeEntry = new TimeEntry__c(Service_Contract__c = project.Id,  isBillable__c = true, 
                                                                        Description__c = timeNote, StartTime__c = startDate, EndTime__c = endDate, CaseId__c = task.ID);
        insert timeEntry;
        ClientReport report = new ClientReport(project.Id);
        
        System.assert(report.projectId == project.Id);
        System.assert(report.title == projectName);
        System.assert(report.contractedHours == contractedHours);
        System.assert(report.tasks != null);
        for( ClientReportTask reportTask : report.tasks ){
        	System.assertEquals(Date.today(), reportTask.executionDate);
            System.assertEquals(taskName, reportTask.taskName);
            System.assertEquals(timeNote, reportTask.notes);
        	System.assertEquals(timeHours, reportTask.duration);
        }
    }
    
    @isTest
    public static void clientReportController(){
        ApexPages.currentPage().getParameters().put('pId','000000000000000');
        new ClientReportController();
    }
    
}