force-app/main/default/objects/ClockifySettings__c/ClockifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Clockify Settings</label>
</CustomObject>

force-app/main/default/objects/ClockifySettings__c/fields/autoCloseDays__c.field-meta.xml
<CustomField>
    <fullName>autoCloseDays__c</fullName>
    <label>autoCloseDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/LogsLifeTime__c.field-meta.xml
<CustomField>
    <fullName>LogsLifeTime__c</fullName>
    <description>Em dias</description>
    <label>LogsLifeTime</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Create_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Create_Key__c</fullName>
    <label>Signing Create Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Delete_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Delete_Key__c</fullName>
    <label>Signing Delete Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Stop_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Stop_Key__c</fullName>
    <label>Signing Stop Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClockifySettings__c/fields/Signing_Update_Key__c.field-meta.xml
<CustomField>
    <fullName>Signing_Update_Key__c</fullName>
    <label>Signing Update Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomSettings_TEST.cls
@isTest
public with sharing class CustomSettings_TEST {
    private static final String BATCH_NAME = 'Delete Logs Batch';
    @testSetup
    static void init() {
        ClockifySettings__c  cS = new ClockifySettings__c();
        insert cS;
    }
    
    @isTest
    static void testGetCustomSettings() {
        ClockifySettings__c cS = CustomSettings_CTRL.getCustomSettings();
        System.assertNotEquals(null, cS);
    }
    
    @isTest
    static void testSetCustomSettingsPositive() {
        CustomSettings_CTRL.setCustomSettings(30, 7, 'teste','teste', 'teste', 'teste', 'teste');
        ClockifySettings__c  ic = [SELECT id,Signing_Create_Key__c, autoCloseDays__c, Signing_Delete_Key__c, Signing_Stop_Key__c, Signing_Update_Key__c, workspaceId__c, LogsLifeTime__c
                                           FROM ClockifySettings__c];
        System.assertEquals(ic.Signing_Create_Key__c, 'teste', 'Create Key error!');
        System.assertEquals(ic.Signing_Delete_Key__c, 'teste', 'Delete Key error!');
        System.assertEquals(ic.Signing_Stop_Key__c, 'teste', 'Stop Key error!');
        System.assertEquals(ic.Signing_Update_Key__c, 'teste', 'Update Key error!');
        System.assertEquals(ic.workspaceId__c, 'teste', 'WorkspaceId error!');
        System.assertEquals(ic.LogsLifeTime__c, 30, 'Logs Liftime error!');
        System.assertEquals(ic.autoCloseDays__c, 7, 'autoCloseDays error!');
        System.assertEquals(1, [SELECT count() FROM CronTrigger  where CronJobDetail.Name =: BATCH_NAME], 'Erro agendamento');
    }
    
    @isTest
    static void testSetCustomSettingsNegative() {
        String response = CustomSettings_CTRL.setCustomSettings(-1, -1, 'teste','teste', 'teste', 'teste', 'teste');
        System.assertEquals('You missed some fields!', response);
    }
}