force-app/main/default/objects/ClockifySettings__c/ClockifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Clockify Settings</label>
</CustomObject>

force-app/main/default/objects/ClockifySettings__c/fields/LogsLifeTime__c.field-meta.xml
<CustomField>
    <fullName>LogsLifeTime__c</fullName>
    <description>Em dias</description>
    <label>LogsLifeTime</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>What integration is this log from?</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clockify-API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteLogs_Batch.cls
public class DeleteLogs_Batch implements Database.Batchable<sObject>, Schedulable{
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Integer days = Integer.ValueOf(ClockifySettings__c.getInstance().LogsLifeTime__c);
        Date deleteDate = Date.today().addDays(-days);
        return Database.getQueryLocator([SELECT Id 
                                        FROM Integration_Log__c 
                                        WHERE CreatedDate <: deleteDate
                                        AND Source__c = 'Clockify-API']);
    }
    public void execute(Database.BatchableContext bc, List<Integration_Log__c> scope){
        Database.delete(scope, false);
    }
    public void finish(Database.BatchableContext bc){}
    
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new DeleteLogs_Batch());
    }
}