force-app/main/default/objects/ClockifySettings__c/ClockifySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Clockify Settings</label>
</CustomObject>

force-app/main/default/objects/ClockifySettings__c/fields/LogsLifeTime__c.field-meta.xml
<CustomField>
    <fullName>LogsLifeTime__c</fullName>
    <description>Em dias</description>
    <label>LogsLifeTime</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>What integration is this log from?</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clockify-API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeleteLogs_TEST.cls
@isTest
public with sharing class DeleteLogs_TEST {
    @testSetup
    static void init() {
        ClockifySettings__c cS = new ClockifySettings__c();
        cS.LogsLifeTime__c = 30;
        insert cS;
    }
	@isTest
    static void testBatch() {
        Integration_Log__c log = new Integration_Log__c();
        log.Source__c = 'Clockify-API';
        insert log;
        id logId = log.id;
        Test.setCreatedDate(logId, Date.today().addDays(-31));
        Test.startTest();
        Database.executeBatch(new DeleteLogs_Batch());
        Test.stopTest();
        System.assertEquals(0, [SELECT count() FROM Integration_Log__c WHERE id =: logId]);
    }
    
    @isTest
    static void testBatchNegative() {
        Integration_Log__c log = new Integration_Log__c();
        log.Source__c = 'Clockify-API';
        insert log;
        id logId = log.id;
        Test.setCreatedDate(logId, Date.today().addDays(-20));
        Test.startTest();
        Database.executeBatch(new DeleteLogs_Batch());
        Test.stopTest();
        System.assertEquals(1, [SELECT count() FROM Integration_Log__c WHERE id =: logId]);
    }
    @isTest
    static void testSchedule() {
        Integration_Log__c log = new Integration_Log__c();
        log.Source__c = 'Clockify-API';
        insert log;
        id logId = log.id;
        Test.setCreatedDate(logId, Date.today().addDays(-20));
        Test.startTest();
        System.schedule('Teste', '0 0 4 ? * SUN *', new DeleteLogs_Batch());
        Database.executeBatch(new DeleteLogs_Batch());
        Test.stopTest();
        System.assertEquals(1, [SELECT count() FROM Integration_Log__c WHERE id =: logId]);
    }
}