force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Endpoint_Type__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Type__c</fullName>
    <label>Endpoint Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Create-Manually</fullName>
            </value>
            <value>
                <fullName>Create-Timer</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>What integration is this log from?</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clockify-API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationLogCreator.cls
public with sharing class IntegrationLogCreator {
    String source;
    String endpointType;
    String message;
    String requestBody;
    String result;

    public IntegrationLogCreator(String source, String endpointType, String message, String result, String requestBody){
        this.source = source;
        this.endpointType = endpointType;
        this.message = message;
        this.requestBody = requestBody;
        this.result = result;
    }
    public void publish(){
        Integration_Log__c log = new Integration_Log__c();
        log.Source__c = this.source;
        log.Endpoint_Type__c = this.endpointType;
        log.Message__c = this.message;
        log.RequestBody__c = this.requestBody;
        log.Result__c = this.result;
        Database.insert(log);
    }
}