force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Endpoint_Type__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Type__c</fullName>
    <label>Endpoint Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Create-Manually</fullName>
            </value>
            <value>
                <fullName>Create-Timer</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Ignored</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <inlineHelpText>What integration is this log from?</inlineHelpText>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Clockify-API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationLogCreator_Test.cls
@isTest
public with sharing class IntegrationLogCreator_Test {
    @isTest
    public static void testeLogCreation(){
        Test.startTest();
            new IntegrationLogCreator('Clockify-API', 'Delete', 'Teste Message', 'Ignored', 'Teste Body').publish();
        Test.stopTest();
        Integration_Log__c dbLog = [SELECT ID, Source__c, Endpoint_Type__c, Message__c, RequestBody__c, Result__c FROM Integration_Log__c];
        Assert.areEqual('Clockify-API', dbLog.Source__c, 'Wrong source value');
        Assert.areEqual('Delete', dbLog.Endpoint_Type__c, 'Wrong endpoint type value');
        Assert.areEqual('Teste Message', dbLog.Message__c, 'Wrong message value');
        Assert.areEqual('Ignored', dbLog.Result__c, 'Wrong result value');
        Assert.areEqual('Teste Body', dbLog.RequestBody__c, 'Wrong request body value');
    }
}