force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time entries object from Clockify integration, which is integrated with Cases and Accounts</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship from Case object</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field with time entry description to integrate with Clockify</description>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time from Time Entry</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/TrackedTime__c.field-meta.xml
<CustomField>
    <fullName>TrackedTime__c</fullName>
    <description>Time tracked from End Time to Start Time in hours</description>
    <formula>(EndTime__c -  StartTime__c) * 24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tracked Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClientReportTask.cls
public class ClientReportTask {

    public Date executionDate 	{get; set;}
    public String taskName 		{get; set;}
    public String notes 	{get; set;}
    public Decimal duration 	{get; set;}
    
    public ClientReportTask(TimeEntry__c taskTime){
        this.taskName = taskTime.CaseId__r == null ? '' : taskTime.CaseId__r.Subject.escapeEcmaScript();
        this.executionDate = taskTime.StartTime__c.date();
        this.duration = taskTime.TrackedTime__c;
        if( String.isNotBlank(taskTime.Description__c) )
        	this.notes = taskTime.Description__c.escapeEcmaScript();
    }
    
    public static List<ClientReportTask> getClientReportTasks(List<TimeEntry__c> taskTimes){
        List<ClientReportTask> taskList = new List<ClientReportTask>();
        for( TimeEntry__c taskTime : taskTimes ){
            if( String.isNotBlank(taskTime.Description__c) )
            	taskList.add(new ClientReportTask(taskTime));
        }
        return taskList;
    }
}