force-app/main/default/objects/ServiceContract/fields/MonthlyHoursPerContract__c.field-meta.xml
<CustomField>
    <fullName>MonthlyHoursPerContract__c</fullName>
    <label>Monthly Hours Per Contract</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/RemainingMonthlyHours__c.field-meta.xml
<CustomField>
    <fullName>RemainingMonthlyHours__c</fullName>
    <label>Remaining Monthly Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/RemainingTotalHours__c.field-meta.xml
<CustomField>
    <fullName>RemainingTotalHours__c</fullName>
    <label>Remaining Total Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/TotalHoursPerContract__c.field-meta.xml
<CustomField>
    <fullName>TotalHoursPerContract__c</fullName>
    <label>Total Hours Per Contract</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time entries object from Clockify integration, which is integrated with Cases and Accounts</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/isBillable__c.field-meta.xml
<CustomField>
    <fullName>isBillable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to check if the time entry is billable or not. This will reflect on the hours presented to customer and on it&apos;s entitlements</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/TrackedTime__c.field-meta.xml
<CustomField>
    <fullName>TrackedTime__c</fullName>
    <description>Time tracked from End Time to Start Time in hours</description>
    <formula>(EndTime__c -  StartTime__c) * 24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tracked Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProjectHoursCalculator_Batch.cls
public class ProjectHoursCalculator_Batch implements Database.Batchable<sObject>, Schedulable{

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, RemainingTotalHours__c, RemainingMonthlyHours__c, TotalHoursPerContract__c, MonthlyHoursPerContract__c
                                        FROM ServiceContract 
                                        WHERE IsDeleted = FALSE 
                                        AND Status = 'Active']);
    }
    public void execute(Database.BatchableContext bc, List<ServiceContract> scope){
        try{
            ServiceContract sContract = scope[0];
            List<TimeEntry__c> tEntrys = new List<TimeEntry__c>();
            tEntrys.addAll([SELECT ID, TrackedTime__c, CreatedDate
                            FROM TimeEntry__c
                            WHERE Service_Contract__c =:sContract.Id
                            AND isBillable__c = true]);
            Decimal totalHours = sContract.TotalHoursPerContract__c == null ? 0 : sContract.TotalHoursPerContract__c;
            Decimal monthHours = sContract.MonthlyHoursPerContract__c == null ? 0 : sContract.MonthlyHoursPerContract__c;
            for (TimeEntry__c entry : tEntrys) {
                totalHours -= entry.TrackedTime__c;
                if(entry.CreatedDate.month() == Date.today().month()){
                    monthHours -= entry.TrackedTime__c;
                }
            }
            if(sContract.RemainingTotalHours__c != totalHours || sContract.RemainingMonthlyHours__c != monthHours){
                sContract.RemainingTotalHours__c = totalHours;
                sContract.RemainingMonthlyHours__c = monthHours;
                update sContract;
            }   
        }catch(Exception error){
            new IntegrationLogCreator('ProjectHoursCalculator_Batch', 'execute', Json.serialize(new Map<String,String>{'error' => error.getTypeName(), 'message' => error.getMessage(), 'line' => String.valueOf(error.getLineNumber())}), 'Failure', null).publish();
        }
    }
    public void finish(Database.BatchableContext bc){
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                        TotalJobItems, CreatedBy.Email
                        FROM AsyncApexJob 
                        WHERE Id = :bc.getJobId()];
                        new IntegrationLogCreator('ProjectHoursCalculator_Batch', 'finish', Json.serialize(new Map<String,String>{'JobItemsProcessed' => String.valueOf(a.JobItemsProcessed), 'Status' => a.Status, 'TotalJobItems' => String.valueOf(a.TotalJobItems)}), 'Success', null).publish();
    }
    
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new ProjectHoursCalculator_Batch(), 1);
    }
}