force-app/main/default/objects/ServiceContract/fields/TotalHoursPerContract__c.field-meta.xml
<CustomField>
    <fullName>TotalHoursPerContract__c</fullName>
    <label>Total Hours Per Contract</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>Time entries object from Clockify integration, which is integrated with Cases and Accounts</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeEntry__c/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship from Case object</description>
    <label>Case ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Field with time entry description to integrate with Clockify</description>
    <label>Description</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/isBillable__c.field-meta.xml
<CustomField>
    <fullName>isBillable__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Checkbox to check if the time entry is billable or not. This will reflect on the hours presented to customer and on it&apos;s entitlements</description>
    <label>Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/Service_Contract__c.field-meta.xml
<CustomField>
    <fullName>Service_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Contract</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Time_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Start time from Time Entry</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TimeEntry__c/fields/TrackedTime__c.field-meta.xml
<CustomField>
    <fullName>TrackedTime__c</fullName>
    <description>Time tracked from End Time to Start Time in hours</description>
    <formula>(EndTime__c -  StartTime__c) * 24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tracked Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClientReport.cls
public class ClientReport {
    public String projectId		{get; set;}
    public String title 			{get; set;}
    public Date startDate 			{get; set;}
    public Decimal contractedHours	{get; set;}
    public List<ClientReportTask> tasks 	{get; set;} 
    
    public ClientReport(String projectId){
        this.projectId = projectId;
        if( this.isValidProjectId() ){
            setReportData();
        }
    }
    
    public void setReportData(){
        List<ServiceContract> project = [SELECT Id, Name, TotalHoursPerContract__c, StartDate,
                                        (SELECT Id, CaseId__r.Subject, StartTime__c, TrackedTime__c/*, Description__c*/ 
                                        FROM Time_Entries__r 
                                        WHERE isBillable__c = true 
                                        ORDER BY StartTime__c DESC)
                                    FROM ServiceContract 
                                    WHERE Id = :projectId];
        if( !project.isEmpty() ){
        	this.title = project[0].Name.escapeEcmaScript();
            this.contractedHours = project[0].TotalHoursPerContract__c;
        	this.tasks = ClientReportTask.getClientReportTasks(project[0].Time_Entries__r);
            this.startDate = project[0].StartDate;
        }
    }
    
    public Boolean isValidProjectId(){
        return projectId != null && Pattern.matches('[A-Za-z0-9]{15}([A-Za-z0-9]{3}){0,1}', projectId);
    }
}